three_numbers =(1,1,2,3)
print(three_numbers)
print(three_numbers[0])
print(len(three_numbers))
print(three_numbers.count(1))
print(type(three_numbers))

strings =('home','school','work')
bools = (True,False,True)
print(strings)
print(bools)